# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  notificationengine:
    image: notificationengine
    build:
      context: .
      dockerfile: NotificationEngine/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5205:5205
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
